---
title: "HW 09"
author: "Vivek Ramakrishnan"
date: "11/28/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(RCurl)
library(rvest)
library(purrr)
library(magrittr)
library(tidytext)
library(twitteR)
library(knitr)
library(memisc)
library(reshape2)
library(scales)
library(rtweet)
library(tm)
library(caret)
options(digits =3)
set.seed(1234)
```

```{r}
rt <- search_tweets(
  q = 'dke',
  n = 3000,
  include_rts = FALSE
)
rt
```

```{r}
vivek <- get_timeline(user = 'ArianaGrande',
                      n = 4000,
                      include_rts = FALSE,)
vivek
```

```{r}
vivek_tidy <- vivek %>%
  rowid_to_column('ID') %>%
  dplyr::select(text, favorite_count, retweet_count, ID) %>%
     unnest_tokens(output = word, input = text) %>%
   # remove numbers
   filter(!str_detect(word, "^[0-9]*$")) %>%
   # remove stop words
   anti_join(stop_words) %>%
   # stem the words
   mutate(word = SnowballC::wordStem(word))

vivek_tidy$fav <- ifelse(vivek_tidy$favorite_count >= 0 &  vivek_tidy$favorite_count <= 10000, 'very low', 
                        ifelse(vivek_tidy$favorite_count >10000 & vivek_tidy$favorite_count <=100000, 'low',
                         ifelse(vivek_tidy$favorite_count >100000 & vivek_tidy$favorite_count <=300000, 'medium', 
                                ifelse(vivek_tidy$favorite_count >300000 & vivek_tidy$favorite_count <=600000, 'high',
                                ifelse(vivek_tidy$favorite_count >600000, 'very high', 'something else')))))

vivek_tidy
```

```{r}
(vivek_dtm <- vivek_tidy %>%
  count(ID, word) %>%
  cast_dtm(document = ID, term = word, value = n))

removeSparseTerms(vivek_dtm, sparse = .99)
```

```{r}
(vivek_tfidf <- vivek_tidy %>%
  count(fav, word)  %>%
   bind_tf_idf(term = word, document = fav, n = n))


```

```{r}

(vivek_nrc <- vivek_tidy %>%
  inner_join(get_sentiments('nrc')) %>%
  group_by(ID, sentiment))


vivek_nrc %>%
  ungroup %>%
  count(word, sentiment)  %>%
  arrange(desc(n)) %>%
  group_by(sentiment) %>% # 
  mutate(top = seq_along(word)) %>%
  # retain top 15 frequent words
  filter(top <= 15) %>%
  # create barplot
  ggplot(aes(x = -top, y = n, fill = sentiment)) + 
  geom_col(color = "black") +
  # print words in plot instead of as axis labels
  geom_text(aes(label = word), hjust = "left", nudge_y = 100) +
  labs(title = "Most frequent words in Tweets",
       x = NULL,
       y = "Word count") +
  facet_wrap( ~ sentiment, ncol = 5) +
  coord_flip() +
  theme(legend.position = "none",
        # rotate x text
        axis.text.x = element_text(angle = 45, hjust = 1),
        # remove tick marks and text on y-axis
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank())



```


```{r}
(vivek_nrc <- vivek_tidy %>%
  inner_join(get_sentiments('afinn')) %>%
  group_by(ID, score))


vivek_nrc %>%
  ungroup %>%
  count(word, score)  %>%
  arrange(desc(n)) %>%
  group_by(score) %>% # 
  mutate(top = seq_along(word)) %>%
  # retain top 15 frequent words
  filter(top <= 15) %>%
  # create barplot
  ggplot(aes(x = -top, y = n, fill = score)) + 
  geom_col(color = "black") +
  # print words in plot instead of as axis labels
  geom_text(aes(label = word), hjust = "left", nudge_y = 100) +
  labs(title = "Most frequent words in Tweets",
       x = NULL,
       y = "Word count") +
  facet_wrap( ~ score, ncol = 5) +
  coord_flip() +
  theme(legend.position = "none",
        # rotate x text
        axis.text.x = element_text(angle = 45, hjust = 1),
        # remove tick marks and text on y-axis
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank())
```



```{r}
plot_vivek <- vivek_tfidf %>%
  arrange(desc(tf_idf))  %>%
  mutate(word = factor(word, levels = rev(unique(word))))


# graph the top 10 tokens for 4 categories
plot_vivek %>%
  group_by(fav) %>%
  top_n(10) %>%
  ungroup() %>%
  ggplot(aes(word, tf_idf)) +
  geom_col() +
  labs(x = NULL, y = "tf-idf") +
  facet_wrap(~fav, scales = "free") +
  coord_flip()




```
```{r}
(vivek_tfidf1 <- vivek_tidy %>%
  inner_join(get_sentiments('nrc')) %>%
  count(fav, sentiment)  %>%
  bind_tf_idf(term = sentiment, document = fav, n = n))

plot_vivek <- vivek_tfidf1 %>%
  arrange(desc(tf_idf))  %>%
  mutate(sentiment = factor(sentiment, levels = rev(unique(sentiment))))



# graph the top 10 tokens for 4 categories
plot_vivek %>%
  group_by(fav) %>%
  top_n(12) %>%
  ungroup() %>%
  ggplot(aes(sentiment, tf)) +
  geom_col() +
  labs(x = NULL, y = "tf-idf") +
  facet_wrap(~fav, scales = "free") +
  coord_flip()

```



```{r}
plot_vivek %>%
  group_by(fav) %>%
  top_n(10)
```



```{r}
vivek_nrc <- vivek_tidy %>%
  inner_join(get_sentiments('afinn')) %>%
  group_by(ID, fav) %>%
  summarize(avg_score = sum(score))

ariana_count <- vivek_tidy %>%
  count(fav)

vivek_nrc2 <- vivek_nrc %>%
    group_by(fav) %>%
    summarize(score = mean(avg_score))  %>%
    inner_join(ariana_count) %>%
    mutate(sign = ifelse(score > 0, 'positive', 
                         ifelse(score < 0, 'negative', 'something else')))


kable(vivek_nrc2)

ggplot(vivek_nrc2) + geom_bar(aes(x=reorder(fav, -score), score, fill = sign), stat = 'identity') 

vivek_tidy
```

```{r}

```



```{r}
vivek_nrc <- vivek_tidy %>%
  inner_join(get_sentiments('nrc'))

vivek_nrc
```



```{r}


vivek_nrc %>%
  # summarize count per word per book
  count(fav, word) %>%
  # highest freq on top
  arrange(desc(n)) %>% 
  # identify rank within group
  group_by(fav) %>% # 
  mutate(top = seq_along(word)) %>%
  # retain top 15 frequent words
  filter(top <= 10) %>%
  # create barplot
  ggplot(aes(x = -top, y = n, fill = fav)) + 
  geom_col(color = "black") +
  # print words in plot instead of as axis labels
  geom_text(aes(label = word), hjust = "left", nudge_y = 100) +
  labs(title = "Most frequent words in Ariana Grande's Tweets",
       x = NULL,
       y = "Word count") +
  facet_wrap( ~ fav) +
  coord_flip() +
  theme(legend.position = "none",
        # rotate x text
        axis.text.x = element_text(angle = 45, hjust = 1),
        # remove tick marks and text on y-axis
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank())
```

```{r}
vivek_nrc %>%
  # summarize count per word per book
  count(fav, sentiment) %>%
  # highest freq on top
  arrange(desc(n)) %>% 
  # identify rank within group
  group_by(fav) %>% # 
  mutate(top = seq_along(sentiment)) %>%
  # retain top 15 frequent words
  filter(top <= 15) %>%
  # create barplot
  ggplot(aes(x = -top, y = n, fill = fav)) + 
  geom_col(color = "black") +
  # print words in plot instead of as axis labels
  geom_text(aes(label = sentiment), hjust = "left", nudge_y = 100) +
  labs(title = "Most frequent words in Ariana Grande's Tweets",
       x = NULL,
       y = "Word count") +
  facet_wrap( ~ fav) +
  coord_flip() +
  theme(legend.position = "none",
        # rotate x text
        axis.text.x = element_text(angle = 45, hjust = 1),
        # remove tick marks and text on y-axis
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank())
```

```{r}
(vivek_tidy <- vivek %>%
  rowid_to_column('ID') %>%
  dplyr::select(text, favorite_count, retweet_count, ID, created_at) %>%
     unnest_tokens(output = word, input = text) %>%
   # remove numbers
   filter(!str_detect(word, "^[0-9]*$")) %>%
   # remove stop words
   anti_join(stop_words) %>%
   # stem the words
   mutate(word = SnowballC::wordStem(word)))

```

```{r}
(time <- vivek_tidy %>% 
  separate(created_at, c("date", 'time')))

View(time)

```



Ariana Grande is largely considered one of the most prolific artists **of all time**. Essential to being a popstar in 2018 is your social media presence. 




